"""empty message

Revision ID: 39917d1a09db
Revises: 5bf8ab26f419
Create Date: 2022-05-07 09:42:27.328106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39917d1a09db'
down_revision = '5bf8ab26f419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
